#!/bin/bash

#All alerts to be executed in case of detecting anomalies in the network

arp_ping_alert="[WARNING] ! ARP Request Detected"
nd_ns_alert="[WARNING] ! ND Neighbor Solicitation Detected"
nd_ra_alert="[WARNING] ! ND Router Advertisement Detected"
icmp_ping_alert="[WARNING] ! ICMP Echo Detected"
icmpv6_ping_alert="[WARNING] ! ICMPv6 Echo Detected"
icmp_mask_alert="[WARNING] ! ICMP Mask Request Detected"
icmp_timestamp_alert="[WARNING] ! ICMP Timestamp Request Detected"
tcp_connection_alert="[WARNING] ! TCP Connection Established"
sctp_scan_alert="[WARNING] ! SCTP Scan Detected"
tcp_DoS_alert="[WARNING] ! Possible TCP Denial Of Service Attack"
udp_DoS_alert="[WARNING] ! Possible UDP Denial Of Service Attack"
syn_scan_alert="[WARNING] ! TCP SYN Scan detected"
ack_scan_alert="[WARNING] ! TCP ACK Scan detected"
null_scan_alert="[WARNING] ! TCP Null Scan Detected"
fin_scan_alert="[WARNING] ! TCP FIN Scan Detected"
xmas_scan_alert="[WARNING] ! TCP XMAS Scan Detected"
udp_scan_alert="[WARNING] ! UDP Scan detected"
banner_grabing_alert="[WARNING] ! Nmap Banner Grabing Detected"
OS_detection_alert="[WARNING] ! Nmap OS Recognition Detected"
brute_force_alert="[WARNING] ! Brute Force Attack Detected"
zone_transfer_alert="[WARNING] ! DNS Zone Transfer Deteced"
inverse_query_alert="[WARNING] ! DNS Inverse Query Detected"
vlan_hopping_alert="[WARNING] ! Vlan Hopping Attack Detected"
arp_poisoning_alert="[WARNING] ! ARP Poisoning Attack Detected"
stp_manipulation_alert="[WARNING] ! STP Manipulation Detected"
mac_flooding_alert="[WARNING] ! MAC Flooding Attack Detected"
nse_scripting_alert="[WARNING] ! Nmap NSE Detected"
sql_injection_alert="[WARNING] ! Possible SQL Injection Detected"
ipv4_fragmentation_alert="[WARNING] ! IPv4 Fragments Detected"
